#!/bin/bash
#PBS -l nodes=1:ppn=20
#PBS -l walltime=01:00:00
#PBS -N myjob0
#PBS -o myjoba.out
#PBS -e myjob.err
#PBS -q workq
#PBS -A loni_cyen405
#PBS -m e
#PBS -M cyu004@latech.edu

work="/home/cyu004/lab2"
XFILE="lab2_a"
cd $work

./$XFILE
